import Head from 'next/head'
import Header from '../components/header'
import Nav from '../components/nav'
import  Results from '../components/Results'
import requests from '../utils/requests'

export default function Home({results}) {
  console.log(results)

  return (
    <div >
      <Head>
        <title>Hulu 2.0</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {/* Header */}
      <Header/>

      {/* Nav Bar */}
      <Nav />

      {/* Results */}
      <Results result={results} />
    </div>
  )
}

export async function getServerSideProps(context){
  const genre = context.query.genre;
  const request = await fetch(
    `https://api.themoviedb.org/3${
      requests[genre]?.category || requests[0].category
    }`
    ).then(res => res.json());

    return {
      props: {
        results: request.results,
    }
  }
}
